[build]
builder = "nixpacks"

[build.nixpacksConfig]
aptPkgs = [
  "libglib2.0-0t64",
  "libnspr4",
  "libnss3",
  "libdbus-1-3",
  "libatk1.0-0t64",
  "libatk-bridge2.0-0t64",
  "libatspi2.0-0t64",
  "libx11-6",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libxcb1",
  "libxkbcommon0",
  "libasound2t64",
  "libxss1",
  "libgtk-3-0",
  "libpangocairo-1.0-0",
  "libcups2"
]
